export const ADD_BUSINESS = 'ADD_BUSINESS';
export const BUSINESSES_LOADING = 'BUSINESSES_LOADING';
export const BUSINESSES_FAILED = 'BUSINESSES_FAILED';
export const ADD_BUSINESSES = 'ADD_BUSINESSES';