export const ADD_BUSINESS = 'ADD_BUSINESS';

export const ADD_BUSINESSES = 'ADD_BUSINESSES';
export const BUSINESSES_LOADING = 'BUSINESSES_LOADING';
export const BUSINESSES_FAILED = 'BUSINESSES_FAILED';

export const ADD_HAPPYHOUR = 'ADD_HAPPYHOUR';

export const ADD_HAPPYHOURS = 'ADD_HAPPYHOURS';
export const HAPPYHOURS_LOADING = 'HAPPYHOURS_LOADING';
export const HAPPYHOURS_FAILED = 'HAPPYHOURS_FAILED';

export const CHANGE_VOTE = 'CHANGE_VOTE';
